(defun color-theme-huangbop-default ()
  (interactive)
  (color-theme-install
   '(color-theme-huangbop-default
      ((background-color . "#000000")
      (background-mode . light)
      (border-color . "#6d2927")
      (cursor-color . "#c70700")
      (foreground-color . "#bfbfbf")
      (mouse-color . "black"))
     (fringe ((t (:background "#6d2927"))))
     (mode-line ((t (:foreground "#acb300" :background "#63100d"))))
     (region ((t (:background "#2c5219"))))
     (font-lock-builtin-face ((t (:foreground "#ff1a0f"))))
     (font-lock-comment-face ((t (:foreground "#787878"))))
     (font-lock-function-name-face ((t (:foreground "#ff00cb"))))
     (font-lock-keyword-face ((t (:foreground "#00e604"))))
     (font-lock-string-face ((t (:foreground "#6688f0"))))
     (font-lock-type-face ((t (:foreground"#0f4eff"))))
     (font-lock-constant-face ((t (:foreground "#e0eb00"))))
     (font-lock-variable-name-face ((t (:foreground "#05fffa"))))
     (minibuffer-prompt ((t (:foreground "#0028eb" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))

(provide 'color-theme-huangbop)
